### ISSUE TITLE
iwm_rx_tx_cmd_single 613 OUTPUT_ERROR status=132

### ISSUE THREAD

**Issue by s0ullight** [zxystd/itlwm#62]
[log.txt](https://github.com/zxystd/itlwm/files/4555116/log.txt)

The 3160 firmware gives a fatal error right after iwm_rx_tx_cmd_single 613 OUTPUT_ERROR status=132.
It happens twice in the attached log.
On a side note: unloading the kext causes system crash

**Comment by zxystd** [comment]
Yes, it is still a tx issue, just because of the packet error or bus transfer wrong(not sure), then the router refuse the packet. really a strange problem, the sequence is just convert frame to 802.11 which from `outputPacket`, and do bus send through `iwm_tx` (even non encrypted WiFi also contains this problem, so we can eliminate the problem of algorithm).Network down, firmware crash, slow upload speed, unstable ping stat... these problems are the same cause of this.

**Comment by mehmetyukcell** [comment]
> Yes, it is still a tx issue, just because of the packet error or bus transfer wrong(not sure), then the router refuse the packet. really a strange problem, the sequence is just convert frame to 802.11 which from `outputPacket`, and do bus send through `iwm_tx` (even non encrypted WiFi also contains this problem, so we can eliminate the problem of algorithm).Network down, firmware crash, slow upload speed, unstable ping stat... these problems are the same cause of this.

When can the kext command come out?

**Comment by s0ullight** [comment]
Commit 81 fixed this crash
